spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.75
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/admin
      database: employeemgmt
